name: Build Windows

on:
  workflow_call:
    inputs:
      build-mode:
        required: true
        type: string
        default: 'releasedbg'
      upload-build-for-next-job:
        required: true
        type: boolean
        default: false
    outputs:
      str-version:
        description: "Halcyon version string"
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022]
        arch: [x64]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    outputs:
      version: ${{ steps.output-version.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1

      - name: Cache xmake dependencies
        uses: actions/cache@v4
        with:
          path: ~/AppData/Local/.xmake/packages
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 3.0.9
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: ${{ matrix.os }}

      - name: Configure xmake and install dependencies
        run: xmake config --arch=${{ matrix.arch }} --mode=${{ inputs.build-mode }} --yes -vD

      - name: Build with xmake
        run: |
          xmake -y
          echo "HALCYON_BUILD_DIR=build/windows/${{ matrix.arch }}/${{ inputs.build-mode }}/" >> $env:GITHUB_ENV

      - name: Output distribution binaries
        run: |
          xmake install -o distrib
          cp -Force -Recurse distrib/bin/* ${{ env.HALCYON_BUILD_DIR }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          cache-dependency-path: Code/skyrim_ui/pnpm-lock.yaml
          cache: 'pnpm'

      - name: Build the legacy web UI assets
        run: |
          pnpm --prefix Code/skyrim_ui/ install
          pnpm --prefix Code/skyrim_ui/ deploy:production
          cp -r Code/skyrim_ui/dist/UI ${{ env.HALCYON_BUILD_DIR }}

      - id: output-version
        shell: pwsh
        run: |
          $version = git describe --tags 2>$null
          if (-not $version) {
            $version = "halcyon-$(git rev-parse --short HEAD)"
          }
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Upload build files for packaging
        if: ${{ inputs.upload-build-for-next-job }}
        uses: actions/upload-artifact@v4
        with:
          name: internal-job-files
          retention-days: 1
          path: |
            ${{ env.HALCYON_BUILD_DIR }}
            GameFiles/Skyrim/
